export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).end()
  const { course } = req.body

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: Georgia, serif; max-width: 750px; margin: 40px auto; color: #1a1a1a; line-height: 1.6; }
  h1 { font-size: 28px; color: #1B3A6B; border-bottom: 2px solid #1B3A6B; padding-bottom: 10px; }
  .meta { color: #666; font-size: 14px; margin-bottom: 30px; }
  .description { font-style: italic; color: #444; margin-bottom: 30px; font-size: 16px; }
  h2 { font-size: 18px; color: #1B3A6B; margin-top: 30px; margin-bottom: 6px; }
  h3 { font-size: 13px; text-transform: uppercase; letter-spacing: 0.05em; color: #888; margin: 12px 0 6px; }
  ul { margin: 0; padding-left: 20px; }
  li { margin-bottom: 4px; font-size: 14px; color: #444; }
  .section { border-left: 3px solid #1B3A6B; padding-left: 16px; margin-bottom: 24px; }
  .footer { margin-top: 40px; font-size: 12px; color: #aaa; border-top: 1px solid #eee; padding-top: 12px; }
</style>
</head>
<body>
<h1>${course.title}</h1>
<div class="meta">Estimated time: ${course.estimatedHours} hours &nbsp;|&nbsp; ${course.sections.length} sections</div>
<div class="description">${course.description}</div>
${course.sections.map((s, i) => `
<div class="section">
  <h2>${i + 1}. ${s.title}</h2>
  <p style="font-size:14px;color:#555;margin:4px 0 10px">${s.description}</p>
  <h3>Topics Covered</h3>
  <ul>${s.subtopics.map(t => `<li>${t}</li>`).join('')}</ul>
  <h3>Key Takeaways</h3>
  <ul>${s.keyTakeaways.map(t => `<li>${t}</li>`).join('')}</ul>
</div>`).join('')}
<div class="footer">Generated by SoothSeyer</div>
</body>
</html>`

  res.setHeader('Content-Type', 'text/html')
  res.send(html)
}
